### ISSUE TITLE
404 NOT FROM

### ISSUE THREAD

**Issue by CS6** [Sup3r-Us3r/MyDotfiles#1]
https://github.com/Sup3r-Us3r/dotfiles/blob/master/config/bspwm/bspwmrc
404 NOT FROM
i'm installing For Bspwm
{touch bspwmrc && nano bspwmrc ///Paste this = https://github.com/Sup3r-Us3r/dotfiles/blob/master/config/bspwm/bspwmrc
$ sudo chmod +x bspwmrc}

**Comment by CS6** [comment]
I would also like to know whether you can install on my habits UBUNTU ro debian

**Comment by Sup3r-Us3r** [comment]
Friend these dependencies you can find in Debian / Ubuntu based systems just use the package manager of your system, some of these packages you probably will not find in the package manager of your distro so you need to look for them and compile in the same hand, so you can Use these customizations on your system, I will soon make a video of other customizations covering various systems OK :D
